version: '3.8'

# Simple project docker-compose.yml 
# This file includes the master Coolify build configuration
# You can add service overrides below if needed for your specific project

include:
  - https://raw.githubusercontent.com/joshfedo/coolify_build/main/docker-compose.master.yml

# Add any project-specific service overrides here
# services:
#   magento:
#     image: shinsenter/magento:${PHP_IMAGE_TAG:-php8.3-nginx}  # Override PHP version
#     environment:
#       - CUSTOM_ENV_VAR=value  # Add custom environment variables
