version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - REGISTRY_URL=${REGISTRY_URL:-docker-reg.ubuntu.orb.local}
      - REGISTRY_USER=${REGISTRY_USER:-testuser}
      - REGISTRY_PASS=${REGISTRY_PASS:-testpassword}
      - COMMIT_SHA=${COMMIT_SHA}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    working_dir: /workspace
    command: |
      sh -c "
        dockerd-entrypoint.sh &
        sleep 5
        echo 'Starting build process'
        /deploy.sh
        echo 'Build and push completed'
      "
    restart: "no"
