version: '3.8'

services:
  build-and-push:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-reg.ubuntu.orb.local/magento-init:${COMMIT_SHA:-latest}
    environment:
      - REGISTRY_URL=docker-reg.ubuntu.orb.local
      - REGISTRY_USER=testuser
      - REGISTRY_PASS=testpassword
      - IMAGE_TAG=${COMMIT_SHA:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      sh -c "
        echo 'Image built during docker-compose build phase'
        echo 'Tagging and pushing to registry'
        echo '$$REGISTRY_PASS' | docker login $$REGISTRY_URL -u $$REGISTRY_USER --password-stdin
        docker tag docker-reg.ubuntu.orb.local/magento-init:$$IMAGE_TAG docker-reg.ubuntu.orb.local/magento-init:latest
        docker push docker-reg.ubuntu.orb.local/magento-init:$$IMAGE_TAG
        docker push docker-reg.ubuntu.orb.local/magento-init:latest
        echo 'Push complete'
      "
    restart: "no"
