version: '3.8'

services:
  magento:
    image: shinsenter/magento:${PHP_IMAGE_TAG:-php8.2-nginx}
    networks:
      - magento-network
      - coolify-network
    volumes:
      - magento-code:/var/www/html
    environment:
      - M2_DB_HOST=db
      - M2_DB_NAME=${COOLIFY_DATABASE_NAME:-magento}
      - M2_DB_USER=${COOLIFY_DATABASE_USER:-magento}
      - M2_DB_PASSWORD=${COOLIFY_DATABASE_PASSWORD:-magento_password}
      - M2_REDIS_HOST=redis
      - M2_SEARCH_ENGINE=opensearch
      - M2_OPENSEARCH_HOST=opensearch
      - M2_BASE_URL=https://${COOLIFY_FQDN:-localhost}/
      - M2_ADMIN_USER=${COOLIFY_ENV_ADMIN_USER:-admin}
      - M2_ADMIN_PASSWORD=${COOLIFY_ENV_ADMIN_PASSWORD:-Password123!}
      - COOLIFY_PREVIEW_DEPLOYMENT=${COOLIFY_PREVIEW_DEPLOYMENT}
      # Coolify Magic Environment Variables
      - SERVICE_FQDN_MAGENTO
      - SERVICE_URL_MAGENTO
      - SERVICE_PASSWORD_MAGENTO
    expose:
      - "80"
    # Note: NO ports declaration - Coolify handles routing via Traefik
    depends_on:
      - db
      - redis
      - opensearch
