version: '3.8'
services:
  db-backup:
    image: mariadb:${DB_IMAGE_TAG:-10.6}
    networks:
      - magento-network
    environment:
      - COOLIFY_DATABASE_NAME
      - COOLIFY_DATABASE_USER
      - COOLIFY_DATABASE_PASSWORD
      - COOLIFY_PREVIEW_DEPLOYMENT
    volumes:
      - db-backups:/backups
    command: |
      bash -c "
        set -e
        if [ \"$$COOLIFY_PREVIEW_DEPLOYMENT\" == \"true\" ]; then
          echo '⏭️ Skipping backup service on preview environment.'
          exit 0
        fi
        
        # Statically set the hostname to \"db\"
        echo '⏳ Backup service waiting for database connection at host \"db\"...'
        for i in {1..120}; do
          if mysqladmin ping -h \"db\" --silent; then
            echo '✅ Database connection established.'
            break
          fi
          if [ $$i -eq 120 ]; then
            echo '❌ Database connection timed out after 2 minutes.'
            exit 1
          fi
          sleep 1
        done

        while true; do
          echo '🚀 Starting nightly database backup...'
          # The hostname is now hardcoded for maximum reliability.
          mysqldump --no-tablespaces -u root -proot_password $COOLIFY_DATABASE_NAME > /backups/latest.sql
          echo '✅ Nightly backup completed successfully.'
          echo '📅 Scheduling next backup in 24 hours.'
          sleep 86400
        done
      "
    restart: "unless-stopped"
    profiles:
      - backup
    depends_on:
      - db
