version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_IMAGE_TAG:-2.5.0}
    networks:
      - magento-network
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
